FROM python:3.6

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        apt-utils   \
        gcc         \
        libssl-dev && \
    apt-get autoremove -y && \
    apt-get clean
    
# Upgrade pip
RUN pip install --upgrade pip

COPY . /client

WORKDIR /client

RUN pip install -e .
RUN pip install aiofiles asgiref httpbin starlette wsproto

EXPOSE 4434/udp
